### ISSUE TITLE
RFE: Update dependencies

### ISSUE THREAD

**Issue by ignatenkobrain** [YaLTeR/wl-clipboard-rs#14]
Hello,

I'm now packaging wl-clipboard-rs because I asked to switch to cli-clipboard in `gitui` which works great on Wayland (thanks @YaLTeR for creating this library) but one thing that is somewhat blocking me is outdated dependencies here.

* `nix` is 0.16, but 0.18 is available
* `wayland-*` are 0.23, but 0.27 are available

If you could update those and release new version of a crate, would be very much appreciated.

**Comment by YaLTeR** [comment]
Hi, thanks for the issue.

> `nix` is 0.16, but 0.18 is available

Probably as easy as bumping the version number.

> `wayland-*` are 0.23, but 0.27 are available

This one is a big update, thankfully I've had most of it done in a local branch for a while, just need to get around to finishing that work.

**Comment by ignatenkobrain** [comment]
> This one is a big update, thankfully I've had most of it done in a local branch for a while, just need to get around to finishing that work.

Ohh, great to hear!

**Comment by ignatenkobrain** [comment]
@YaLTeR Also you probably want to drop `failure` in favor of `anyhow` and `exitfailure` completely because in the main() you can return Error for quite some time in Rust and anyhow will make it nice.

**Comment by YaLTeR** [comment]
Yeah, good idea.

**Comment by YaLTeR** [comment]
I updated `nix` and `wayland-rs` on the master branch, do you mind giving it a test?

**Comment by ignatenkobrain** [comment]
@YaLTeR sure! I've tried gitui with cli-clipboard and overrode `wl-clipboard-rs` dependency to use git master from this repo and it compiles and works on Fedora 34 with GNOME under Wayland. I'm able to copy text into the buffer :)

**Comment by YaLTeR** [comment]
> works on Fedora 34 with GNOME under Wayland

Uh, as far as I know Mutter doesn't implement wlr-data-control. :)

**Comment by YaLTeR** [comment]
I've published v0.4.1 with updated dependencies. Replacement of failure with thiserror will happen with a version bump later™.
