### ISSUE TITLE
Move binaries to another crate to clean up dependencies

### ISSUE THREAD

**Issue by EthanYidong** [YaLTeR/wl-clipboard-rs#15]
Using this crate as a library requires pulling and building `structopt` which is unnecessary and introduces 100+ extra dependencies. Creating a workspace and a separate crate for the binaries would solve this.

**Comment by YaLTeR** [comment]
Yeah, that definitely doesn't sound right. Is there a way to specify that a dependency is only for the binaries maybe?

**Comment by bugaevc** [comment]
Is `dev-dependencies` not it?

Also, perhaps take a look at [argh](https://lib.rs/crates/argh), which is a lot like structopt, but leaner & lighter in dependencies.

**Comment by YaLTeR** [comment]
> Is `dev-dependencies` not it?

Apparently not.

**Comment by YaLTeR** [comment]
If I'm not mistaken, dependencies only used in binaries are `mime_guess`, `stderrlog`, `exitfailure` and `structopt`.

**Comment by mike7b4** [comment]
You can use workspaces and cleanup the repo. keep project in this repo split code binaries and lib in two crates something like:

in root Cargo.toml you just put
[workspace]
members = ["libwl-clipboard", "wl-clipboard-tools"]

then in the subdirs you add the "real" cargo.toml and its dependencies.

libwl-clipboard   # publish as new crate
wl-clipboard-tools # publish as second crate (the binaries)

mark the old crate as deprecated.

**Comment by YaLTeR** [comment]
Closed by #19.
