### ISSUE TITLE
structopt should be an opt in feature and not part of the lib

### ISSUE THREAD

**Issue by mike7b4** [YaLTeR/wl-clipboard-rs#17]
when I added cli-clipboard crate in https://gitlab.com/mike7b4/passmando I noticed that it did have dependecies on structopt but after some more investigation I  found out that it is wl-clipboard-rs that has dependencies on structopt. 

I am not against clap/structopt by itself but since this is a library I think it should be an opt in.

   ├── wl-clipboard-rs v0.4.1
│   │   ├── derive-new v0.5.9 (proc-macro)
│   │   │   ├── proc-macro2 v1.0.36 (*)
│   │   │   ├── quote v1.0.14 (*)
│   │   │   └── syn v1.0.85 (*)
│   │   ├── derive_more v0.99.17 (proc-macro)
│   │   │   ├── convert_case v0.4.0
│   │   │   ├── proc-macro2 v1.0.36 (*)
│   │   │   ├── quote v1.0.14 (*)
│   │   │   └── syn v1.0.85 (*)
│   │   │   [build-dependencies]
│   │   │   └── rustc_version v0.4.0
│   │   │       └── semver v1.0.4
│   │   ├── exitfailure v0.5.1
│   │   │   └── failure v0.1.8 (*)
│   │   ├── failure v0.1.8 (*)
│   │   ├── libc v0.2.112
│   │   ├── log v0.4.14 (*)
│   │   ├── mime_guess v2.0.3
│   │   │   ├── mime v0.3.16
│   │   │   └── unicase v2.6.0
│   │   │       [build-dependencies]
│   │   │       └── version_check v0.9.4
│   │   │   [build-dependencies]
│   │   │   └── unicase v2.6.0 (*)
│   │   ├── nix v0.18.0
│   │   │   ├── bitflags v1.3.2
│   │   │   ├── cfg-if v0.1.10
│   │   │   └── libc v0.2.112
│   │   ├── os_pipe v0.9.2
│   │   │   └── libc v0.2.112
│   │   ├── stderrlog v0.4.3
│   │   │   ├── atty v0.2.11 (*)
│   │   │   ├── chrono v0.4.19
│   │   │   │   ├── libc v0.2.112
│   │   │   │   ├── num-integer v0.1.44
│   │   │   │   │   └── num-traits v0.2.14
│   │   │   │   │       [build-dependencies]
│   │   │   │   │       └── autocfg v1.0.1
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── autocfg v1.0.1
│   │   │   │   ├── num-traits v0.2.14 (*)
│   │   │   │   └── time v0.1.43
│   │   │   │       └── libc v0.2.112
│   │   │   ├── log v0.4.14 (*)
│   │   │   ├── termcolor v1.1.2
│   │   │   └── thread_local v0.3.4
│   │   │       ├── lazy_static v0.2.11
│   │   │       └── unreachable v1.0.0
│   │   │           └── void v1.0.2
│   │   ├── structopt v0.3.25
│   │   │   ├── clap v2.34.0
│   │   │   │   ├── ansi_term v0.12.1
│   │   │   │   ├── atty v0.2.11 (*)
│   │   │   │   ├── bitflags v1.3.2
│   │   │   │   ├── strsim v0.8.0
│   │   │   │   ├── term_size v0.3.2
│   │   │   │   │   └── libc v0.2.112
│   │   │   │   ├── textwrap v0.11.0
│   │   │   │   │   ├── term_size v0.3.2 (*)
│   │   │   │   │   └── unicode-width v0.1.9
│   │   │   │   ├── unicode-width v0.1.9
│   │   │   │   └── vec_map v0.8.2
│   │   │   ├── lazy_static v1.4.0
│   │   │   └── structopt-derive v0.4.18 (proc-macro)
│   │   │       ├── heck v0.3.3
│   │   │       │   └── unicode-segmentation v1.8.0
│   │   │       ├── proc-macro-error v1.0.4 (*)
│   │   │       ├── proc-macro2 v1.0.36 (*)
│   │   │       ├── quote v1.0.14 (*)
│   │   │       └── syn v1.0.85 (*)
│   │   ├── tempfile v3.3.0
│   │   │   ├── cfg-if v1.0.0
│   │   │   ├── fastrand v1.6.0
│   │   │   ├── libc v0.2.112
│   │   │   └── remove_dir_all v0.5.3
│   │   ├── tree_magic v0.2.3
│   │   │   ├── fnv v1.0.7
│   │   │   ├── lazy_static v1.4.0
│   │   │   ├── nom v3.2.1
│   │   │   │   └── memchr v1.0.2
│   │   │   │       └── libc v0.2.112
│   │   │   ├── parking_lot v0.10.2
│   │   │   │   ├── lock_api v0.3.4
│   │   │   │   │   └── scopeguard v1.1.0
│   │   │   │   └── parking_lot_core v0.7.2
│   │   │   │       ├── cfg-if v0.1.10
│   │   │   │       ├── libc v0.2.112
│   │   │   │       └── smallvec v1.8.0
│   │   │   └── petgraph v0.5.1
│   │   │       ├── fixedbitset v0.2.0
│   │   │       └── indexmap v1.8.0 (*)
│   │   ├── wayland-client v0.27.0
│   │   │   ├── bitflags v1.3.2
│   │   │   ├── downcast-rs v1.2.0
│   │   │   ├── libc v0.2.112
│   │   │   ├── nix v0.17.0
│   │   │   │   ├── bitflags v1.3.2
│   │   │   │   ├── cfg-if v0.1.10
│   │   │   │   ├── libc v0.2.112
│   │   │   │   └── void v1.0.2
│   │   │   ├── wayland-commons v0.27.0
│   │   │   │   ├── nix v0.17.0 (*)
│   │   │   │   ├── once_cell v1.9.0
│   │   │   │   ├── smallvec v1.8.0
│   │   │   │   └── wayland-sys v0.27.0
│   │   │   │       [build-dependencies]
│   │   │   │       └── pkg-config v0.3.24
│   │   │   └── wayland-sys v0.27.0 (*)
│   │   │   [build-dependencies]
│   │   │   └── wayland-scanner v0.27.0
│   │   │       ├── proc-macro2 v1.0.36 (*)
│   │   │       ├── quote v1.0.14 (*)
│   │   │       └── xml-rs v0.8.4
│   │   └── wayland-protocols v0.27.0
│   │       ├── bitflags v1.3.2
│   │       ├── wayland-client v0.27.0 (*)
│   │       └── wayland-commons v0.27.0 (*)
│   │       [build-dependencies]
│   │       └── wayland-scanner v0.27.0 (*)

**Comment by YaLTeR** [comment]
This makes sense to me. Is it possible to specify a dependency "just for binaries"?

**Comment by YaLTeR** [comment]
Actually, I think this is a duplicate of https://github.com/YaLTeR/wl-clipboard-rs/issues/15
