### ISSUE TITLE
Update `wayland-*` to v0.30

### ISSUE THREAD

**Issue by daxpedda** [YaLTeR/wl-clipboard-rs#36]
Relevant changelogs:
- https://github.com/Smithay/wayland-rs/blob/v0.30.0/wayland-client/CHANGELOG.md
- https://github.com/Smithay/wayland-rs/blob/v0.30.0/wayland-protocols-wlr/CHANGELOG.md
- https://github.com/nix-rust/nix/blob/v0.26.2/CHANGELOG.md#0260---2022-11-29

I tried to upgrade it myself but realized this is gonna be harder then expected, I'm leaving the basic legwork here: https://github.com/daxpedda/wl-clipboard-rs/tree/wayland-v0.30.

Main motivation is to allow `arboard` to upgrade as well.

**Comment by YaLTeR** [comment]
Hmm, right. Thanks for the heads up!

**Comment by YaLTeR** [comment]
Hey, I'm back to having free time, so I'm picking this up.

**Comment by YaLTeR** [comment]
I've finished the port, could you give it a try?

**Comment by YaLTeR** [comment]
I published v0.8.0 which uses wayland-rs 0.31.
