### ISSUE TITLE
Bug: when i use sudo wl-paste, a error occur

### ISSUE THREAD

**Issue by CNCSMonster** [YaLTeR/wl-clipboard-rs#48]
```
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
Failed to connect to a Wayland server: No such file or directory
Note: WAYLAND_DISPLAY is unset (falling back to wayland-0)
Note: XDG_RUNTIME_DIR is unset
```

**Comment by YaLTeR** [comment]
The Wayland socket (like the X11 socket) is user-specific. When you use `sudo`, your environment variables get unset, including the variable that sets your user's runtime dir with the sockets.

In general, you shouldn't run Wayland clients with sudo (and wl-paste is a Wayland client).
