### ISSUE TITLE
zwlr_data_control_manager_v1 version 2 -- Remediation?

### ISSUE THREAD

**Issue by rrichardson** [YaLTeR/wl-clipboard-rs#8]
I am on fedora 30,  but wl-clip fails with this message: 
```
Error: A required Wayland protocol (zwlr_data_control_manager_v1 version 2) is not supported by the compositor
```
I am unfamiliar with the wayland ecosystem.  Is there a way to easily rectify this, or does it require upgrading my wayland installation?

**Comment by bugaevc** [comment]
Shameless plug: please try [wl-clipboard](https://github.com/bugaevc/wl-clipboard/) :)

**Comment by YaLTeR** [comment]
Hello! The supported Wayland protocols depend on the Wayland compositor that you use. Do you use GNOME, KDE, or perhaps something else? As far as I'm aware, `zwlr_data_control_manager_v1` is currently supported only by [sway](https://github.com/swaywm/sway) and other [wlroots](https://github.com/swaywm/wlroots)-based compositors. For other compositors for the time being you should indeed try the regular wl-clipboard, where most of the functionality should work via other protocols.

**Comment by rrichardson** [comment]
I'm on Gnome, the fedora default.  

I am a big i3 fan,  so I can give Sway a try.  My issue is that I work remotely and things like Zoom are critical,  so I am reluctant to experiment too much.  

Are there plans to support other protocols in this project?

**Comment by bugaevc** [comment]
It could be possible to implement other protocols in wl-clipboard-rs, but I think @YaLTeR wouldn't approve of it. The thing is, using those other protocols from tools like wl-clipboard[-rs] requires making use of a focus stealing hack, whereas wlr-data-control allows clipboard tools to work cleanly. wl-clipboard implements those other protocols out of necessity (because I want it to work on all the compositors), not because it's pretty.

So the right question to ask is whether GNOME has plans to implement wlr-data-control, and [the answer is no](https://gitlab.gnome.org/GNOME/mutter/issues/524#note_472761). But there's [this](https://gitlab.gnome.org/bugaevc/mutter/tree/wlr-data-control).

**Comment by YaLTeR** [comment]
My plan was indeed to try to refrain from implementing the focus-stealing hacks. Ideally, other compositors would support wlr-data-control, or some successor of it. There should be some movement in that direction with Wayland protocol governance starting to become more sorted out. Then either GNOME changes their mind and implements the protocol, or they provide some replacement for it, or they just stick to their own in-house thing.

Either way if there's enough demand I will consider implementing the focus-stealing hacks, but thus far I think that wl-clipboard-rs is pretty unknown. Maybe that'll change with rust-clipboard finally merging the wl-clipboard-rs PR, who knows.

**Comment by YaLTeR** [comment]
I guess I'll close this since this isn't a concrete request to support focus-stealing hacks with sufficient demand.

**Comment by abitrolly** [comment]
Just got this problem with `wormhole.rs` on Fedora GNOME.
```
[WARN ] Tried to initialize the wayland data control protocol clipboard, but failed. Falling back to the X11 clipboard protocol. The error was: Unknown error while interacting with the clipboard: A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor
```
So what is the current status of the issue? Am I right that:

1. GNOME only supports focus strealing hacks for apps to copy to clipboard
2. Rust lib doesn't want to support these hacks (because?)

**Comment by bugaevc** [comment]
> GNOME only supports focus strealing hacks for apps to copy to clipboard

Well, GNOME doesn't _support_ the hacks either, but they happen to work on GNOME. For now anyway.

Also, it's wrong to phrase this as if it's some deficiency in GNOME. There's just no way to access clipboard from an unfocused client in Wayland, _unless_ a compositor chooses to implement the completely optional, non-standardized wlroots protocol extension. If your compositor does, you're in luck (or not, considering that background apps can steal clipboard contents without notice), but it's generally not something that can/should be expected of a compositor to provide.

> Rust lib doesn't want to support these hacks (because?)

[See above](https://github.com/YaLTeR/wl-clipboard-rs/issues/8#issuecomment-542365429).

**Comment by abitrolly** [comment]
@bugaevc for `wormhole.rs` it is completely fine to paste to clipboard with focused client. Why is it impossible?

**Comment by YaLTeR** [comment]
What is wormhole.rs? Is it a GUI app? In that case it should use the normal Wayland clipboard protocols (data device), not wl-clipboard-rs.

**Comment by abitrolly** [comment]
@YaLTeR console app https://github.com/magic-wormhole/magic-wormhole.rs

**Comment by YaLTeR** [comment]
Well there's supposedly OSC 52 for terminal apps (which makes the *terminal* use the normal Wayland protocol to interact with the clipboard, since it is the focused client), but in reality everyone just spawns `wl-copy` and `wl-paste` instead. Which are *not the terminal* so they have to spawn a new window and hope that it gets auto-focused by the compositor—the "focus stealing hacks" in question.

**Comment by abitrolly** [comment]
I don't see that it uses `wl-paste`. https://github.com/search?q=repo%3Amagic-wormhole%2Fmagic-wormhole.rs%20wl-paste&type=code

**Comment by YaLTeR** [comment]
I meant what terminal apps usually end up doing. Like neovim or helix.

**Comment by abitrolly** [comment]
Uses https://crates.io/crates/arboard

https://github.com/magic-wormhole/magic-wormhole.rs/blob/040e4229dc4ecb62609e7674c7de41be105c0738/cli/src/main.rs#L21

And `arboard` seems to use `wl-clipboard-rs` https://crates.io/crates/arboard/3.4.1/dependencies

**Comment by YaLTeR** [comment]
Yes, which unfortunately doesn't work on GNOME. Currently due to the lack of the focus stealing workaround, and if GNOME turns on strict focus stealing prevention by default, it won't work in general.

**Comment by abitrolly** [comment]
But it is possible to paste to clipboard without stealing focus, right? The `OSC 52 for terminal apps` - how to use it?

**Comment by YaLTeR** [comment]
Can't help you with OSC 52 but there should be info on the internet. It's a terminal control sequence for working with clipboard.

**Comment by abitrolly** [comment]
So let me summarize this.

1. Wayland doesn't have secure API to let applications write to clipboard
2. Programs use unofficial hacks to write to clipboard
3. Hacks are insecure, because they steal focus
4. `wl-clipboard-rs` don't want to be insecure
5. `wl-clipboard-rs` doesn't work with Wayland

**Comment by YaLTeR** [comment]
> Hacks are insecure, because they steal focus

More like, stealing focus isn't gonna always work (it already doesn't always work). Compositors will enable more and more focus stealing prevention mechanisms.

> wl-clipboard-rs don't want to be insecure

Tbh it's just nontrivial effort for something that is pretty hacky
